<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ItManagement.AgentEnrollment</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Server/Core/Core.csproj" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <InternalsVisibleTo Include="AgentEnrollment.Tests" />
  </ItemGroup>

</Project>
