// <auto-generated />
using System;
using ItManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ConsoleDbContext))]
    [Migration("20260912003114_EnrollmentGrantOperations")]
    partial class EnrollmentGrantOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItManagement.Core.AuditRecord", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceIp")
                        .HasColumnType("text");

                    b.Property<string>("TargetId")
                        .HasColumnType("text");

                    b.HasKey("EnvironmentId", "Id");

                    b.HasIndex("EnvironmentId", "OccurredAt", "Id");

                    b.ToTable("Audit", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.ChangeApproval", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.HasKey("EnvironmentId", "Id");

                    b.HasIndex("EnvironmentId", "PlanId")
                        .IsUnique();

                    b.ToTable("Approvals", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.ChangePlan", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImmutablePlanJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PlanHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("EnvironmentId", "Id");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.ChangePlanItem", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("ExpectedVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EnvironmentId", "Id");

                    b.HasIndex("EnvironmentId", "PlanId");

                    b.ToTable("PlanItems", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.DeviceAsset", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("EnvironmentId", "Id");

                    b.ToTable("DeviceAssets", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.DeviceTag", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("EnvironmentId", "Id");

                    b.HasIndex("EnvironmentId", "Key")
                        .IsUnique();

                    b.ToTable("DeviceTags", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.DeviceTagAssignment", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("EnvironmentId", "TagId", "ObjectId");

                    b.HasIndex("EnvironmentId", "ObjectId", "TagId");

                    b.ToTable("DeviceTagAssignments", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.DeviceUserLink", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("EnvironmentId", "Id");

                    b.HasIndex("EnvironmentId", "UserId", "Id");

                    b.ToTable("DeviceUserLinks", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.DirectoryFavorite", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EnvironmentId", "PrincipalId", "ObjectId");

                    b.ToTable("Favorites", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.DirectoryGroupMapping", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupSid")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid");

                    b.HasKey("EnvironmentId", "Id");

                    b.HasIndex("EnvironmentId", "RoleId");

                    b.HasIndex("EnvironmentId", "ScopeId");

                    b.ToTable("GroupMappings", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.EnrollmentGrantOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApproverOperatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AuthorizationNotAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DirectoryGeneration")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DirectoryObjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<long>("EnvironmentVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("MappingCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RecipientKeyFingerprint")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("RecipientSpki")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterOperatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServerDeviceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipientKeyFingerprint")
                        .IsUnique();

                    b.HasIndex("EnvironmentId", "ApprovalId")
                        .IsUnique();

                    b.HasIndex("EnvironmentId", "PlanId")
                        .IsUnique();

                    b.HasIndex("EnvironmentId", "PlanId", "RequesterId", "PlanHash");

                    b.HasIndex("EnvironmentId", "ApprovalId", "PlanId", "PlanHash", "ApproverId");

                    b.HasIndex("RecipientKeyFingerprint", "EnvironmentId", "PlanId", "RequesterId", "RequestId");

                    b.ToTable("EnrollmentGrantOperations", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.EnrollmentGrantRecipientReservation", b =>
                {
                    b.Property<byte[]>("Fingerprint")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RequestDigest")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.HasKey("Fingerprint");

                    b.HasIndex("EnvironmentId", "PlanId")
                        .IsUnique();

                    b.HasIndex("EnvironmentId", "RequesterId", "RequestId")
                        .IsUnique();

                    b.ToTable("EnrollmentGrantRecipientReservations", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.EnvironmentMembership", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.HasKey("EnvironmentId", "PrincipalId");

                    b.HasIndex("PrincipalId");

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.ManagedEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalDns")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<string>("DefaultLocale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Environments", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.OutboxMessage", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("EnvironmentId", "Id");

                    b.ToTable("Outbox", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.Principal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("Principals", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.Role", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BuiltInKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("EnvironmentId", "Id");

                    b.HasIndex("EnvironmentId", "Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.RoleAssignment", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid");

                    b.HasKey("EnvironmentId", "Id");

                    b.HasIndex("EnvironmentId", "PrincipalId");

                    b.HasIndex("EnvironmentId", "RoleId");

                    b.HasIndex("EnvironmentId", "ScopeId");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.RolePermission", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Permission")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("EnvironmentId", "RoleId", "Permission");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.SavedFilter", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Search")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("EnvironmentId", "PrincipalId", "Id");

                    b.HasIndex("EnvironmentId", "TagId");

                    b.ToTable("SavedFilters", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.Scope", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IncludeDescendants")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("EnvironmentId", "Id");

                    b.ToTable("Scopes", (string)null);
                });

            modelBuilder.Entity("ItManagement.Persistence.AuthCeremony", b =>
                {
                    b.Property<string>("IdHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionHash")
                        .HasColumnType("text");

                    b.HasKey("IdHash");

                    b.HasIndex("PrincipalId");

                    b.ToTable("Ceremonies", (string)null);
                });

            modelBuilder.Entity("ItManagement.Persistence.DirectoryObjectRecord", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DistinguishedName")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<Guid>("Generation")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ObjectSid")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<Guid[]>("OuAncestry")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<Guid?>("ParentOuId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ProtectionKnown")
                        .HasColumnType("boolean");

                    b.Property<string>("SamAccountName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("UsnChanged")
                        .HasColumnType("bigint");

                    b.HasKey("EnvironmentId", "Id");

                    b.HasIndex("EnvironmentId", "Generation", "Kind", "Id");

                    b.ToTable("DirectoryObjects", (string)null);
                });

            modelBuilder.Entity("ItManagement.Persistence.DirectorySyncState", b =>
                {
                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("Generation")
                        .HasColumnType("uuid");

                    b.Property<string>("NamingContext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceServer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EnvironmentId", "Id");

                    b.HasIndex("EnvironmentId")
                        .IsUnique();

                    b.ToTable("DirectorySync", (string)null);
                });

            modelBuilder.Entity("ItManagement.Persistence.LocalCredential", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("PrincipalId");

                    b.ToTable("LocalCredentials", (string)null);
                });

            modelBuilder.Entity("ItManagement.Persistence.Passkey", b =>
                {
                    b.Property<string>("CredentialId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("CredentialId");

                    b.HasIndex("PrincipalId");

                    b.ToTable("Passkeys", (string)null);
                });

            modelBuilder.Entity("ItManagement.Persistence.PasskeyEnrollmentGrant", b =>
                {
                    b.Property<string>("IdHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.HasKey("IdHash");

                    b.HasIndex("PrincipalId");

                    b.ToTable("EnrollmentGrants", (string)null);
                });

            modelBuilder.Entity("ItManagement.Persistence.PlatformSession", b =>
                {
                    b.Property<string>("IdHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StepUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdHash");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PrincipalId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("ItManagement.Persistence.PrincipalPreference", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("PrincipalId");

                    b.ToTable("Preferences", (string)null);
                });

            modelBuilder.Entity("ItManagement.Persistence.SecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SecurityEvents", (string)null);
                });

            modelBuilder.Entity("ItManagement.Core.AuditRecord", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.ChangeApproval", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItManagement.Core.ChangePlan", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.ChangePlan", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.ChangePlanItem", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItManagement.Core.ChangePlan", null)
                        .WithMany("Items")
                        .HasForeignKey("EnvironmentId", "PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.DeviceAsset", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.DeviceTag", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.DeviceTagAssignment", b =>
                {
                    b.HasOne("ItManagement.Core.DeviceTag", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.DeviceUserLink", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.DirectoryFavorite", b =>
                {
                    b.HasOne("ItManagement.Core.EnvironmentMembership", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.DirectoryGroupMapping", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItManagement.Core.Role", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItManagement.Core.Scope", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "ScopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.EnrollmentGrantOperation", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItManagement.Core.ChangePlan", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "PlanId", "RequesterId", "PlanHash")
                        .HasPrincipalKey("EnvironmentId", "Id", "RequesterId", "PlanHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItManagement.Core.ChangeApproval", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "ApprovalId", "PlanId", "PlanHash", "ApproverId")
                        .HasPrincipalKey("EnvironmentId", "Id", "PlanId", "PlanHash", "ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItManagement.Core.EnrollmentGrantRecipientReservation", null)
                        .WithMany()
                        .HasForeignKey("RecipientKeyFingerprint", "EnvironmentId", "PlanId", "RequesterId", "RequestId")
                        .HasPrincipalKey("Fingerprint", "EnvironmentId", "PlanId", "RequesterId", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.EnrollmentGrantRecipientReservation", b =>
                {
                    b.HasOne("ItManagement.Core.ChangePlan", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.EnvironmentMembership", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItManagement.Core.Principal", null)
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.OutboxMessage", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.Role", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.RoleAssignment", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItManagement.Core.EnvironmentMembership", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItManagement.Core.Role", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItManagement.Core.Scope", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "ScopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.RolePermission", b =>
                {
                    b.HasOne("ItManagement.Core.Role", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.SavedFilter", b =>
                {
                    b.HasOne("ItManagement.Core.EnvironmentMembership", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItManagement.Core.DeviceTag", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId", "TagId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ItManagement.Core.Scope", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Persistence.AuthCeremony", b =>
                {
                    b.HasOne("ItManagement.Core.Principal", null)
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Persistence.DirectoryObjectRecord", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Persistence.DirectorySyncState", b =>
                {
                    b.HasOne("ItManagement.Core.ManagedEnvironment", null)
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Persistence.LocalCredential", b =>
                {
                    b.HasOne("ItManagement.Core.Principal", null)
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Persistence.Passkey", b =>
                {
                    b.HasOne("ItManagement.Core.Principal", null)
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Persistence.PasskeyEnrollmentGrant", b =>
                {
                    b.HasOne("ItManagement.Core.Principal", null)
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Persistence.PlatformSession", b =>
                {
                    b.HasOne("ItManagement.Core.Principal", null)
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Persistence.PrincipalPreference", b =>
                {
                    b.HasOne("ItManagement.Core.Principal", null)
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ItManagement.Core.ChangePlan", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
