<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../Infrastructure/Persistence/Persistence.csproj" /><FrameworkReference Include="Microsoft.AspNetCore.App" /></ItemGroup>
</Project>
